// <auto-generated />
using System;
using HR_Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR_Platform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR_Platform.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateOnly(1990, 5, 24),
                            Email = "petar.petrovic@gmail.com",
                            Name = "Petar Petrovic",
                            PhoneNumber = "+381623457998"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateOnly(2002, 12, 4),
                            Email = "anajovanovic@gmail.com",
                            Name = "Ana Jovanovic",
                            PhoneNumber = "+381656783207"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateOnly(1986, 3, 5),
                            Email = "pera.peric@gmail.com",
                            Name = "Pera Peric",
                            PhoneNumber = "+381630096381"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateOnly(1999, 8, 30),
                            Email = "jelena.djordjevic@gmail.com",
                            Name = "Jelena Djordjevic",
                            PhoneNumber = "+381623358998"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateOnly(2000, 5, 12),
                            Email = "marko.markovic@gmail.com",
                            Name = "Marko Markovic",
                            PhoneNumber = "+381612766438"
                        });
                });

            modelBuilder.Entity("HR_Platform.Models.CandidateSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("CandidateId", "SkillId")
                        .IsUnique();

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidateId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            CandidateId = 1,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 3,
                            CandidateId = 1,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 4,
                            CandidateId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 5,
                            CandidateId = 2,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 6,
                            CandidateId = 2,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 7,
                            CandidateId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 8,
                            CandidateId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 9,
                            CandidateId = 3,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 10,
                            CandidateId = 4,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 11,
                            CandidateId = 4,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 12,
                            CandidateId = 4,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 13,
                            CandidateId = 5,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 14,
                            CandidateId = 5,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 15,
                            CandidateId = 5,
                            SkillId = 3
                        });
                });

            modelBuilder.Entity("HR_Platform.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "English"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Database Design"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 8,
                            Name = "German"
                        });
                });

            modelBuilder.Entity("HR_Platform.Models.CandidateSkill", b =>
                {
                    b.HasOne("HR_Platform.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Models.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HR_Platform.Models.Candidate", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("HR_Platform.Models.Skill", b =>
                {
                    b.Navigation("CandidateSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
